version: "3"

services:
  db:
    image: mdillon/postgis:latest
    ports:
      - 5432:5432

  app:
    build: .
    command: ./entrypoints/docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/kevares-api
      - gems:/gems
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    tty: true
    stdin_open: true

volumes:
  db:
  gems: