default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis
  postgis_schema: public
  schema_search_path: public,postgis
  pool: 5
  host: postgres
  username: postgres
  password: ''

development:
  <<: *default
  database: kevares_api_development

test:
  <<: *default
  database: kevares_api_test

production:
  <<: *default
  database: kevares_api_production
  username: kevares_api
  password: <%= ENV['KEVARES_API_DATABASE_PASSWORD'] %>
